// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for BeginOAuthParamsProvider.
const (
	BeginOAuthParamsProviderGithub BeginOAuthParamsProvider = "github"
	BeginOAuthParamsProviderGoogle BeginOAuthParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the BeginOAuthParamsProvider enum.
func (e BeginOAuthParamsProvider) Valid() bool {
	switch e {
	case BeginOAuthParamsProviderGithub:
		return true
	case BeginOAuthParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for OauthCallbackParamsProvider.
const (
	OauthCallbackParamsProviderGithub OauthCallbackParamsProvider = "github"
	OauthCallbackParamsProviderGoogle OauthCallbackParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the OauthCallbackParamsProvider enum.
func (e OauthCallbackParamsProvider) Valid() bool {
	switch e {
	case OauthCallbackParamsProviderGithub:
		return true
	case OauthCallbackParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for GetCandlesParamsInterval.
const (
	GetCandlesParamsIntervalN1day   GetCandlesParamsInterval = "1day"
	GetCandlesParamsIntervalN1month GetCandlesParamsInterval = "1month"
	GetCandlesParamsIntervalN1week  GetCandlesParamsInterval = "1week"
)

// Valid indicates whether the value is a known member of the GetCandlesParamsInterval enum.
func (e GetCandlesParamsInterval) Valid() bool {
	switch e {
	case GetCandlesParamsIntervalN1day:
		return true
	case GetCandlesParamsIntervalN1month:
		return true
	case GetCandlesParamsIntervalN1week:
		return true
	default:
		return false
	}
}

// Defines values for GetQuotesParamsInterval.
const (
	GetQuotesParamsIntervalN1day   GetQuotesParamsInterval = "1day"
	GetQuotesParamsIntervalN1month GetQuotesParamsInterval = "1month"
	GetQuotesParamsIntervalN1week  GetQuotesParamsInterval = "1week"
)

// Valid indicates whether the value is a known member of the GetQuotesParamsInterval enum.
func (e GetQuotesParamsInterval) Valid() bool {
	switch e {
	case GetQuotesParamsIntervalN1day:
		return true
	case GetQuotesParamsIntervalN1month:
		return true
	case GetQuotesParamsIntervalN1week:
		return true
	default:
		return false
	}
}

// AddWatchlistRequest defines model for AddWatchlistRequest.
type AddWatchlistRequest struct {
	// SymbolCode 追加する銘柄コード（例: AAPL, 7203.T）
	SymbolCode string `json:"symbol_code"`
}

// CandleResponse defines model for CandleResponse.
type CandleResponse struct {
	// Close 終値
	Close float64 `json:"close"`

	// High 高値
	High float64 `json:"high"`

	// Low 安値
	Low float64 `json:"low"`

	// Open 始値
	Open float64 `json:"open"`

	// Time 日付（YYYY-MM-DD形式）
	Time string `json:"time"`

	// Volume 出来高
	Volume int64 `json:"volume"`
}

// CompanyAnalysisRequest defines model for CompanyAnalysisRequest.
type CompanyAnalysisRequest struct {
	// CompanyName 分析対象の企業名
	CompanyName string `json:"company_name"`
}

// CompanyAnalysisResponse defines model for CompanyAnalysisResponse.
type CompanyAnalysisResponse struct {
	// CompanyName 分析対象の企業名
	CompanyName string `json:"company_name"`

	// Summary AI生成の企業分析サマリー
	Summary string `json:"summary"`
}

// DetectedLogoResponse defines model for DetectedLogoResponse.
type DetectedLogoResponse struct {
	// Confidence 信頼度スコア（0.0 ~ 1.0）
	Confidence float32 `json:"confidence"`

	// Name 検出された企業名
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error エラーメッセージ
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status サービスステータス
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email メールアドレス
	Email string `json:"email"`

	// Password パスワード
	Password string `json:"password"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// QuoteResponse defines model for QuoteResponse.
type QuoteResponse struct {
	// Change 前日比（close - prev_close）
	Change float64 `json:"change"`

	// ChangePercent 前日比率（%）。prev_closeが0の場合は0
	ChangePercent float64 `json:"change_percent"`

	// Close 最新終値
	Close float64 `json:"close"`

	// Closes スパークライン用の終値配列（古い→新しい順、最大bars本）。bars=0の場合は含まれない
	Closes *[]float64 `json:"closes,omitempty"`

	// Code 銘柄コード（例: AAPL, 7203.T）
	Code string `json:"code"`

	// PrevClose 前日終値
	PrevClose float64 `json:"prev_close"`

	// Time 最新足の日付（YYYY-MM-DD形式）
	Time string `json:"time"`
}

// ReorderWatchlistRequest defines model for ReorderWatchlistRequest.
type ReorderWatchlistRequest struct {
	// Codes 新しい順序での銘柄コード一覧
	Codes []string `json:"codes"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	// Email メールアドレス
	Email string `json:"email"`

	// Password パスワード（12文字以上）
	Password string `json:"password"`
}

// SymbolItem defines model for SymbolItem.
type SymbolItem struct {
	// Code 銘柄コード（例: AAPL, 7203.T）
	Code string `json:"code"`

	// LogoUrl Twelve DataのロゴURL（未取得時はnull）
	LogoUrl *string `json:"logo_url"`

	// Name 企業名
	Name string `json:"name"`
}

// WatchlistItem defines model for WatchlistItem.
type WatchlistItem struct {
	// Id ウォッチリストエントリのID
	Id int64 `json:"id"`

	// SortKey 表示順序
	SortKey int `json:"sort_key"`

	// SymbolCode 銘柄コード（例: AAPL, 7203.T）
	SymbolCode string `json:"symbol_code"`
}

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// BeginOAuthParamsProvider defines parameters for BeginOAuth.
type BeginOAuthParamsProvider string

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// OauthCallbackParamsProvider defines parameters for OauthCallback.
type OauthCallbackParamsProvider string

// GetCandlesParams defines parameters for GetCandles.
type GetCandlesParams struct {
	// Interval 時間間隔
	Interval *GetCandlesParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`

	// Outputsize 取得件数（1〜5000。範囲外の値が指定された場合は400を返す）
	Outputsize *int `form:"outputsize,omitempty" json:"outputsize,omitempty"`
}

// GetCandlesParamsInterval defines parameters for GetCandles.
type GetCandlesParamsInterval string

// AnalyzeCompanyParams defines parameters for AnalyzeCompany.
type AnalyzeCompanyParams struct {
	// XCSRFToken CSRFトークン（Double Submit Cookieパターン）。
	// ログイン時にSet-Cookieで発行された csrf_token Cookie の値を、変更系リクエストでこのヘッダーに設定します。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// DetectLogoMultipartBody defines parameters for DetectLogo.
type DetectLogoMultipartBody struct {
	// Image ロゴ検出対象の画像ファイル（最大10MB）
	Image openapi_types.File `json:"image"`
}

// DetectLogoParams defines parameters for DetectLogo.
type DetectLogoParams struct {
	// XCSRFToken CSRFトークン（Double Submit Cookieパターン）。
	// ログイン時にSet-Cookieで発行された csrf_token Cookie の値を、変更系リクエストでこのヘッダーに設定します。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetQuotesParams defines parameters for GetQuotes.
type GetQuotesParams struct {
	// Codes カンマ区切りの銘柄コード（1〜50件、例: AAPL,GOOGL,7203.T）。重複は順序を保って除去される
	Codes string `form:"codes" json:"codes"`

	// Interval 時間間隔
	Interval *GetQuotesParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`

	// Bars スパークライン用に含める直近終値の本数（0〜500）。0の場合はclosesを含めない
	Bars *int `form:"bars,omitempty" json:"bars,omitempty"`
}

// GetQuotesParamsInterval defines parameters for GetQuotes.
type GetQuotesParamsInterval string

// AddToWatchlistParams defines parameters for AddToWatchlist.
type AddToWatchlistParams struct {
	// XCSRFToken CSRFトークン（Double Submit Cookieパターン）。
	// ログイン時にSet-Cookieで発行された csrf_token Cookie の値を、変更系リクエストでこのヘッダーに設定します。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// ReorderWatchlistParams defines parameters for ReorderWatchlist.
type ReorderWatchlistParams struct {
	// XCSRFToken CSRFトークン（Double Submit Cookieパターン）。
	// ログイン時にSet-Cookieで発行された csrf_token Cookie の値を、変更系リクエストでこのヘッダーに設定します。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// RemoveFromWatchlistParams defines parameters for RemoveFromWatchlist.
type RemoveFromWatchlistParams struct {
	// XCSRFToken CSRFトークン（Double Submit Cookieパターン）。
	// ログイン時にSet-Cookieで発行された csrf_token Cookie の値を、変更系リクエストでこのヘッダーに設定します。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// AnalyzeCompanyJSONRequestBody defines body for AnalyzeCompany for application/json ContentType.
type AnalyzeCompanyJSONRequestBody = CompanyAnalysisRequest

// DetectLogoMultipartRequestBody defines body for DetectLogo for multipart/form-data ContentType.
type DetectLogoMultipartRequestBody DetectLogoMultipartBody

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// AddToWatchlistJSONRequestBody defines body for AddToWatchlist for application/json ContentType.
type AddToWatchlistJSONRequestBody = AddWatchlistRequest

// ReorderWatchlistJSONRequestBody defines body for ReorderWatchlist for application/json ContentType.
type ReorderWatchlistJSONRequestBody = ReorderWatchlistRequest
