FROM golang:1.27.2-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# APIサーバ
RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app

ENV TZ=Asia/Tokyo

COPY --from=builder /app/api .
USER nonroot

EXPOSE 8080
CMD ["./api"]
