// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authsqlc

import (
	"context"
	"time"
)

type Querier interface {
	ConsumeRefreshSession(ctx context.Context, arg ConsumeRefreshSessionParams) error
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshSessions(ctx context.Context, expiresAt time.Time) (int64, error)
	FindOAuthAccountByProvider(ctx context.Context, arg FindOAuthAccountByProviderParams) (OauthAccount, error)
	FindRefreshSessionByTokenHash(ctx context.Context, tokenHash []byte) (RefreshSession, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
	LockRefreshSessionByTokenHash(ctx context.Context, tokenHash []byte) (RefreshSession, error)
	LockRefreshSessionForRotation(ctx context.Context, tokenHash []byte) (LockRefreshSessionForRotationRow, error)
	RevokeRefreshSessionFamily(ctx context.Context, arg RevokeRefreshSessionFamilyParams) error
}

var _ Querier = (*Queries)(nil)
