// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package candlessqlc

import (
	"database/sql"
	"time"
)

type Candle struct {
	SymbolCode string
	Interval   string
	Time       time.Time
	Open       float64
	High       float64
	Low        float64
	Close      float64
	Volume     int64
}

type OauthAccount struct {
	UserID      int64
	Provider    string
	ProviderUid string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RefreshSession struct {
	ID         string
	FamilyID   string
	UserID     int64
	TokenHash  []byte
	ExpiresAt  time.Time
	ConsumedAt sql.NullTime
	RevokedAt  sql.NullTime
	ReplacedBy sql.NullString
	CreatedAt  time.Time
}

type Symbol struct {
	Code          string
	Name          string
	Market        string
	Timezone      string
	LogoUrl       sql.NullString
	LogoUpdatedAt sql.NullTime
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Watchlist struct {
	ID         int64
	UserID     int64
	SymbolCode string
	SortKey    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
