// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package candlessqlc

import (
	"context"
)

type Querier interface {
	FindCandlesLimit(ctx context.Context, arg FindCandlesLimitParams) ([]Candle, error)
	FindLatestCandlesBySymbols(ctx context.Context, arg FindLatestCandlesBySymbolsParams) ([]Candle, error)
}

var _ Querier = (*Queries)(nil)
