// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package candlessqlc

import (
	"context"
)

const findCandlesLimit = `-- name: FindCandlesLimit :many
SELECT symbol_code, "interval", "time", open, high, low, close, volume
FROM candles
WHERE symbol_code = $1 AND "interval" = $2
ORDER BY "time" DESC
LIMIT $3
`

type FindCandlesLimitParams struct {
	SymbolCode string
	Interval   string
	Limit      int32
}

func (q *Queries) FindCandlesLimit(ctx context.Context, arg FindCandlesLimitParams) ([]Candle, error) {
	rows, err := q.db.QueryContext(ctx, findCandlesLimit, arg.SymbolCode, arg.Interval, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Candle{}
	for rows.Next() {
		var i Candle
		if err := rows.Scan(
			&i.SymbolCode,
			&i.Interval,
			&i.Time,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
