// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package candlessqlc

import (
	"context"
	"time"
)

const findCandlesLimit = `-- name: FindCandlesLimit :many
SELECT c.symbol_code, c."interval", c."time", c.open, c.high, c.low, c.close, c.volume, s.timezone
FROM candles AS c
JOIN symbols AS s ON s.code = c.symbol_code
WHERE c.symbol_code = $1 AND c."interval" = $2
ORDER BY c."time" DESC
LIMIT $3
`

type FindCandlesLimitParams struct {
	SymbolCode string
	Interval   string
	Limit      int32
}

type FindCandlesLimitRow struct {
	SymbolCode string
	Interval   string
	Time       time.Time
	Open       float64
	High       float64
	Low        float64
	Close      float64
	Volume     int64
	Timezone   string
}

func (q *Queries) FindCandlesLimit(ctx context.Context, arg FindCandlesLimitParams) ([]FindCandlesLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, findCandlesLimit, arg.SymbolCode, arg.Interval, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindCandlesLimitRow{}
	for rows.Next() {
		var i FindCandlesLimitRow
		if err := rows.Scan(
			&i.SymbolCode,
			&i.Interval,
			&i.Time,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
